name: Preprocess YAML to Markdown

on:
  push:
    branches:
      - main
    paths:
      - 'contracts/**/*.yaml'
      - 'contracts/**/*.yml'
      - 'preprocess/**'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git log

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Determine if the preprocess code has changed
      - name: Check for changes in preprocess code
        id: preprocess_changes
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q '^preprocess/'; then
            echo "::set-output name=preprocess_changed::true"
          else
            echo "::set-output name=preprocess_changed::false"
          fi

      # Conditionally delete Markdown outputs
      - name: Delete Markdown outputs if preprocess code changed
        if: steps.preprocess_changes.outputs.preprocess_changed == 'true'
        run: |
          echo "Preprocess code changed. Deleting Markdown outputs."
          rm -rf content/posts/*.md
        working-directory: ${{ github.workspace }}

      - name: Build the project
        working-directory: ./preprocess
        run: cargo build --release

      - name: Run the converter
        working-directory: ./preprocess
        run: cargo run --release

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/posts
          git commit -m "Automated conversion of YAML to Markdown [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
